name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Git Semantic Version
      id: version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major("
        minor_pattern: "feat("
        format: "${major}.${minor}.${patch}-prerelease${increment}"
    
    - name: Docker Hub Signin
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Trying signin..."
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Signin successfully."
    
    - name: Build Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t rdgxz/gh-actions:$NEW_VERSION .
        docker build -t rdgxz/gh-actions:latest .
    
    - name: Push Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push rdgxz/gh-actions:$NEW_VERSION
        docker push rdgxz/gh-actions:latest
        
        
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
